name = "zolanight"
description = "ZolaNight is a dark theme inspired by the Tokyo Night color palette"
homepage = "https://zolanight.codedmaster.com"
min_version = "0.18.0"

[author]
name = "mxaddict"
homepage = "https://www.codedmaster.com"
