base_url = "zolanight.codedmaster.com"               # Your site's base URL
title = "ZolaNight Theme Demo"                       # Your site's title
description = "A demo site for the ZolaNight theme." # Your site's description
compile_sass = true                                  # Enable Sass compilation
generate_feeds = true                                # Generate RSS/Atom feeds
feed_limit = 10                                      # Number of items in feeds
feed_filenames = ["atom.xml"]                        # Feed filenames
taxonomies = [{ name = "tags" }]                     # Enable tags taxonomy

[markdown.highlighting]
theme = "catppuccin-mocha" # Code highlighting theme

[extra.zolanight]
theme = "tokyonight"               # Default theme, override as shown above
home_list_latest_blog_posts = true # Set to false to disable listing latest blog posts on the homepage
