base_url = "https://zolanight.codedmaster.com"
title = "ZolaNight Theme Demo"
description = "A demo site for the ZolaNight theme."
compile_sass = true
generate_feeds = true
feed_limit = 10
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags" }]

[markdown.highlighting]
theme = "catppuccin-mocha" # Code highlighting theme

[extra.zolanight]
theme = "tokyonight"
home_list_latest_blog_posts = true
google_analytics_id = "G-7NC6GLJCFS"
ko_fi_url = "https://ko-fi.com/mxaddict"
