base_url = "zolanight.codedmaster.com"
title = "ZolaNight Theme Demo"
description = "A demo site for the ZolaNight theme."
compile_sass = true

generate_feeds = true
feed_limit = 10
feed_filenames = ["atom.xml"]

taxonomies = [{ name = "tags" }]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
author_name = "mxaddict"
author_url = "https://www.codedmaster.com"
list_pages = false

[extra.zolanight]
theme = "tokyonight"

header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/about/", name_en = "/about/" },
  { url = "/blog/", name_en = "/blog/" },
]
